# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import customer_pb2 as customer__pb2


class CustomerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateCustomer = channel.unary_unary(
        '/customer.CustomerService/CreateCustomer',
        request_serializer=customer__pb2.CreateCustomerRequest.SerializeToString,
        response_deserializer=customer__pb2.CreateCustomerResponse.FromString,
        )


class CustomerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateCustomer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateCustomer': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCustomer,
          request_deserializer=customer__pb2.CreateCustomerRequest.FromString,
          response_serializer=customer__pb2.CreateCustomerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'customer.CustomerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
