# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='customer.proto',
  package='customer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63ustomer.proto\x12\x08\x63ustomer\"$\n\x08\x43ustomer\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"<\n\x15\x43reateCustomerRequest\x12#\n\x07request\x18\x01 \x01(\x0b\x32\x12.customer.Customer\">\n\x16\x43reateCustomerResponse\x12$\n\x08response\x18\x01 \x01(\x0b\x32\x12.customer.Customer2h\n\x0f\x43ustomerService\x12U\n\x0e\x43reateCustomer\x12\x1f.customer.CreateCustomerRequest\x1a .customer.CreateCustomerResponse\"\x00\x62\x06proto3')
)




_CUSTOMER = _descriptor.Descriptor(
  name='Customer',
  full_name='customer.Customer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='customer.Customer.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='customer.Customer.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=64,
)


_CREATECUSTOMERREQUEST = _descriptor.Descriptor(
  name='CreateCustomerRequest',
  full_name='customer.CreateCustomerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='customer.CreateCustomerRequest.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=126,
)


_CREATECUSTOMERRESPONSE = _descriptor.Descriptor(
  name='CreateCustomerResponse',
  full_name='customer.CreateCustomerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='customer.CreateCustomerResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=190,
)

_CREATECUSTOMERREQUEST.fields_by_name['request'].message_type = _CUSTOMER
_CREATECUSTOMERRESPONSE.fields_by_name['response'].message_type = _CUSTOMER
DESCRIPTOR.message_types_by_name['Customer'] = _CUSTOMER
DESCRIPTOR.message_types_by_name['CreateCustomerRequest'] = _CREATECUSTOMERREQUEST
DESCRIPTOR.message_types_by_name['CreateCustomerResponse'] = _CREATECUSTOMERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Customer = _reflection.GeneratedProtocolMessageType('Customer', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMER,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:customer.Customer)
  })
_sym_db.RegisterMessage(Customer)

CreateCustomerRequest = _reflection.GeneratedProtocolMessageType('CreateCustomerRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATECUSTOMERREQUEST,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:customer.CreateCustomerRequest)
  })
_sym_db.RegisterMessage(CreateCustomerRequest)

CreateCustomerResponse = _reflection.GeneratedProtocolMessageType('CreateCustomerResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATECUSTOMERRESPONSE,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:customer.CreateCustomerResponse)
  })
_sym_db.RegisterMessage(CreateCustomerResponse)



_CUSTOMERSERVICE = _descriptor.ServiceDescriptor(
  name='CustomerService',
  full_name='customer.CustomerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=192,
  serialized_end=296,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateCustomer',
    full_name='customer.CustomerService.CreateCustomer',
    index=0,
    containing_service=None,
    input_type=_CREATECUSTOMERREQUEST,
    output_type=_CREATECUSTOMERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMERSERVICE)

DESCRIPTOR.services_by_name['CustomerService'] = _CUSTOMERSERVICE

# @@protoc_insertion_point(module_scope)
